
let username = prompt( "Hello, what is your name?");

username ? document.getElementById ('greeting).innerText=(`hello ${username}`) : document.getElementById ('greeting).innerText=('Hello!');
 funtion shakeMagic8Ball(){
    let userQuestion = 'will I adopt a new puppy soon';

    console.log(`${username} has asked - ${userQuestion}`);
    //DO NOT TOUCH THIS CODE!
    let randomNumber = Math.floor(Math.random() * 8);
    
    console.log(`The Magic 8 ball says, ${eightBall}.`);
    function shakeMagic8Ball() {
    
    let eightBall = '';
    
    switch(randomNumber) 
      case 0:
      eightBall = 'It is certain';
      break;
      case 1:
      eightBall = 'It is decidedly so';
      break;
      case 2:
      eightBall = 'Reply hazy try again';
      break;
      case 3:
      eightBall = 'Cannot predict now';
      break;
      case 4:
      eightBall = 'Do not count on it';
      break;
      case 5:
      eightBall = 'My sources say no';
      break;
      case 6:
      eightBall = 'Outlook not so good';
      break;
      case 7:
      eightBall = 'Signs point to yes';
    }
    
    
 
